name: Deploy Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      PROJECT_ID: optimal-relic-481321-h7
      REGION: us-central1
      SERVICE: cloudrun-demo
      REPO: cloudrun-repo
      IMAGE: cloudrun-demo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/106713737818/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions-bot@optimal-relic-481321-h7.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Build & push image with Cloud Build
        run: |
          gcloud builds submit ./cloudrun-demo \
            --tag "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "${{ env.SERVICE }}" \
            --image "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ github.sha }}" \
            --region "${{ env.REGION }}" \
            --allow-unauthenticated


